---
name: Continuous Integration and Continuous Deployment
on:
  push:
    branches:
      - optimised
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check secrets
        run: |
          if [
            -z "${{ secrets.DOCKER_USERNAME }}"
            -o -z "${{ secrets.DOCKER_PASSWORD }}"
          ]; then
            echo "Missing secrets! Please check your secrets."
            exit 1
          fi

          if [
            -z "${{ secrets.AWS_ACCESS_KEY_ID }}"
            -o -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          ]; then
            echo "Missing secrets! Please check your secrets."
            exit 1
          fi

          ]

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docek Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./k8s/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/k8s:$GITHUB_SHA
