---
name: Continuous Integration and Continuous Deployment
on:
  push:
    branches:
      - optimised
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check secrets
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
                echo "DOCKER_USERNAME is not set"
              else
                echo "DOCKER_USERNAME is available"
              fi

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docek Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./k8s/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/k8s:${{ github.sha }}
